apiVersion: apps/v1
kind: Deployment
metadata:
  name: visit-counter-app
  labels:
    app: visit-counter-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: visit-counter-app
  template:
    metadata:
      labels:
        app: visit-counter-app
    spec:
      containers:
        - name: visit-counter-app
          image: mohammadkasim/visit-counter-app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20